[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[secrets]
# Optionally set your Hugging Face token in Streamlit Cloud -> Secrets
# HF_TOKEN = ""
